input.onButtonPressed(Button.A, function () {
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 40)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 40)
    basic.pause(2000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 30)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 30)
    basic.pause(2000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 40)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 40)
    basic.pause(2000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
})
input.onButtonPressed(Button.B, function () {
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 70)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 70)
    basic.pause(2000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CCW, 30)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 30)
    basic.pause(2000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
    DFRobotMaqueenPlus.mototRun(Motors.M1, Dir.CW, 70)
    DFRobotMaqueenPlus.mototRun(Motors.M2, Dir.CW, 70)
    basic.pause(2000)
    DFRobotMaqueenPlus.mototStop(Motors.ALL)
    basic.pause(500)
})
DFRobotMaqueenPlus.I2CInit()
basic.forever(function () {
	
})
